import type { Job } from "../types";

export const allJobs: Job[] = [
  {
    id: "job-1",
    title:
      "Japanese Speaking Associate Analyst, Falcon Complete (アソシエイトアナリスト - ファルコン...",
    company: "CrowdStrike",
    location: "Sydney, New South Wales, Australia (Remote)",
    logo: "https://i.pravatar.cc/100?img=70",
    employmentType: "Full-time",
    postedTime: "18 hours ago",
    alumni: 22,
    datePosted: "Past 24 hours",
    applicantCount: 7,
  },
  {
    id: "job-2",
    title: "Customer Care Agent (Japanese Speaking)",
    company: "Staffbase",
    location: "Sydney, New South Wales, Australia",
    logo: "https://i.pravatar.cc/100?img=52",
    employmentType: "Full-time",
    postedTime: "1 day ago",
    datePosted: "Past 24 hours",
    applicantCount: 5,
  },
  {
    id: "job-3",
    title: "Test Engineer",
    company: "Tech Innovations",
    location: "Sydney, Australia",
    logo: "https://i.pravatar.cc/100?img=53",
    employmentType: "Full-time",
    postedTime: "2 days ago",
    applicants: 45,
    datePosted: "Past week",
    applicantCount: 45,
  },
  {
    id: "job-4",
    title: "Software Test Analyst",
    company: "Digital Solutions",
    location: "Melbourne, Victoria, Australia",
    logo: "https://i.pravatar.cc/100?img=54",
    employmentType: "Contract",
    postedTime: "3 days ago",
    datePosted: "Past week",
    applicantCount: 8,
  },
  {
    id: "job-5",
    title: "Senior Frontend Developer",
    company: "Atlassian",
    location: "Sydney, New South Wales, Australia (Hybrid)",
    logo: "https://i.pravatar.cc/100?img=55",
    employmentType: "Full-time",
    postedTime: "4 days ago",
    alumni: 15,
    datePosted: "Past week",
    applicantCount: 35,
  },
  {
    id: "job-6",
    title: "DevOps Engineer",
    company: "Canva",
    location: "Sydney, New South Wales, Australia",
    logo: "https://i.pravatar.cc/100?img=56",
    employmentType: "Full-time",
    postedTime: "5 days ago",
    alumni: 8,
    datePosted: "Past week",
    applicantCount: 9,
  },
  {
    id: "job-7",
    title: "Product Manager",
    company: "Google",
    location: "Sydney, Australia",
    logo: "https://i.pravatar.cc/100?img=57",
    employmentType: "Full-time",
    postedTime: "1 week ago",
    applicants: 120,
    datePosted: "Past week",
    applicantCount: 120,
  },
  {
    id: "job-8",
    title: "UX/UI Designer",
    company: "Adobe",
    location: "Melbourne, Victoria, Australia",
    logo: "https://i.pravatar.cc/100?img=58",
    employmentType: "Full-time",
    postedTime: "1 week ago",
    alumni: 12,
    datePosted: "Past week",
    applicantCount: 42,
  },
  {
    id: "job-9",
    title: "Backend Developer (Node.js)",
    company: "Shopify",
    location: "Remote Australia",
    logo: "https://i.pravatar.cc/100?img=59",
    employmentType: "Full-time",
    postedTime: "1 week ago",
    datePosted: "Past week",
    applicantCount: 6,
  },
  {
    id: "job-10",
    title: "Data Scientist",
    company: "Microsoft",
    location: "Sydney, New South Wales, Australia",
    logo: "https://i.pravatar.cc/100?img=60",
    employmentType: "Full-time",
    postedTime: "2 weeks ago",
    alumni: 35,
    datePosted: "Past month",
    applicantCount: 85,
  },
  {
    id: "job-11",
    title: "Mobile Developer (React Native)",
    company: "Uber",
    location: "Melbourne, Victoria, Australia",
    logo: "https://i.pravatar.cc/100?img=61",
    employmentType: "Full-time",
    postedTime: "2 weeks ago",
    applicants: 78,
    datePosted: "Past month",
    applicantCount: 78,
  },
  {
    id: "job-12",
    title: "Cloud Solutions Architect",
    company: "Amazon Web Services",
    location: "Sydney, Australia (Hybrid)",
    logo: "https://i.pravatar.cc/100?img=62",
    employmentType: "Full-time",
    postedTime: "2 weeks ago",
    alumni: 18,
    datePosted: "Past month",
    applicantCount: 52,
  },
  {
    id: "job-13",
    title: "Full Stack Engineer",
    company: "Stripe",
    location: "Brisbane, Queensland, Australia",
    logo: "https://i.pravatar.cc/100?img=63",
    employmentType: "Full-time",
    postedTime: "3 weeks ago",
    datePosted: "Past month",
    applicantCount: 64,
  },
  {
    id: "job-14",
    title: "QA Automation Engineer",
    company: "Salesforce",
    location: "Sydney, New South Wales, Australia",
    logo: "https://i.pravatar.cc/100?img=64",
    employmentType: "Contract",
    postedTime: "3 weeks ago",
    alumni: 9,
    datePosted: "Past month",
    applicantCount: 3,
  },
  {
    id: "job-15",
    title: "Security Engineer",
    company: "Cisco",
    location: "Melbourne, Victoria, Australia",
    logo: "https://i.pravatar.cc/100?img=65",
    employmentType: "Full-time",
    postedTime: "3 weeks ago",
    applicants: 42,
    datePosted: "Past month",
    applicantCount: 42,
  },
  {
    id: "job-16",
    title: "Machine Learning Engineer",
    company: "Meta",
    location: "Sydney, Australia (Remote)",
    logo: "https://i.pravatar.cc/100?img=66",
    employmentType: "Full-time",
    postedTime: "1 month ago",
    alumni: 25,
    datePosted: "Past month",
    applicantCount: 145,
  },
  {
    id: "job-17",
    title: "Technical Writer",
    company: "MongoDB",
    location: "Remote Australia",
    logo: "https://i.pravatar.cc/100?img=67",
    employmentType: "Full-time",
    postedTime: "1 month ago",
    datePosted: "Past month",
    applicantCount: 28,
  },
  {
    id: "job-18",
    title: "Site Reliability Engineer",
    company: "Netflix",
    location: "Sydney, New South Wales, Australia",
    logo: "https://i.pravatar.cc/100?img=68",
    employmentType: "Full-time",
    postedTime: "1 month ago",
    alumni: 14,
    datePosted: "Past month",
    applicantCount: 89,
  },
  {
    id: "job-19",
    title: "Business Analyst",
    company: "Deloitte",
    location: "Melbourne, Victoria, Australia",
    logo: "https://i.pravatar.cc/100?img=69",
    employmentType: "Full-time",
    postedTime: "1 month ago",
    applicants: 95,
    datePosted: "Past month",
    applicantCount: 95,
  },
  {
    id: "job-20",
    title: "Scrum Master",
    company: "KPMG",
    location: "Sydney, Australia",
    logo: "https://i.pravatar.cc/100?img=71",
    employmentType: "Contract",
    postedTime: "1 month ago",
    alumni: 20,
    datePosted: "Past month",
    applicantCount: 37,
  },
];
