import type { User } from "../types";
import { chakraCompanyLogo } from "./companies";

export const currentUser: User = {
  id: "1",
  name: "Dzaka Athif",
  title: "Junior Forward Deployed Engineer",
  company: "Chakra | BAW...",
  location: "Sydney, New South Wales",
  avatar: "https://i.pravatar.cc/150?img=33",
  coverImage: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  isVerified: true,
  about:
    "Software Engineer and Master of Information Technology graduate at the University of New South Wales. I'm passionate about programming and exploring various technologies to create high-quality software solutions. My main interests are full-stack web development, backend programming, and data science.",
  connectionCount: 477,
  contactInfo: "dzaka.athif@example.com",
  connectionDegree: "1st",
  currentCompany: "Chakra",
  regions: ["Asia Pacific"],
  experience: [
    {
      id: "exp-1",
      title: "Forward Deployed Engineer",
      company: "Chakra",
      companyLogo: chakraCompanyLogo,
      employmentType: "Full-time",
      startDate: "Oct 2022",
      endDate: undefined,
      location: "Sydney, New South Wales, Australia",
      description:
        "Working on building products with cutting-edge technologies and delivering solutions to enterprise clients.",
    },
    {
      id: "exp-2",
      title: "Software Engineering Intern",
      company: "Tech Innovations Inc",
      employmentType: "Internship",
      startDate: "Jan 2022",
      endDate: "Sep 2022",
      location: "Sydney, Australia",
      description:
        "Developed web applications using React and Node.js. Collaborated with senior engineers on various projects.",
    },
    {
      id: "exp-3",
      title: "Full Stack Developer",
      company: "Digital Solutions Co",
      employmentType: "Full-time",
      startDate: "Jun 2021",
      endDate: "Dec 2021",
      location: "Sydney, Australia",
      description:
        "Built and maintained web applications using modern JavaScript frameworks.",
    },
    {
      id: "exp-4",
      title: "Backend Developer",
      company: "CloudTech Systems",
      employmentType: "Contract",
      startDate: "Jan 2021",
      endDate: "May 2021",
      location: "Remote",
      description: "Developed RESTful APIs and microservices architecture.",
    },
    {
      id: "exp-5",
      title: "Junior Software Engineer",
      company: "StartUp Labs",
      employmentType: "Full-time",
      startDate: "Jul 2020",
      endDate: "Dec 2020",
      location: "Sydney, Australia",
      description:
        "Contributed to various projects in an agile development environment.",
    },
    {
      id: "exp-6",
      title: "Software Development Intern",
      company: "Tech Giants Inc",
      employmentType: "Internship",
      startDate: "Jan 2020",
      endDate: "Jun 2020",
      location: "Sydney, Australia",
      description:
        "Assisted in developing internal tools and automation scripts.",
    },
    {
      id: "exp-7",
      title: "Research Assistant",
      company: "UNSW Sydney",
      employmentType: "Part-time",
      startDate: "Jul 2019",
      endDate: "Dec 2019",
      location: "Sydney, Australia",
      description: "Conducted research in machine learning and data analysis.",
    },
    {
      id: "exp-8",
      title: "Web Developer",
      company: "Freelance",
      employmentType: "Freelance",
      startDate: "Jan 2019",
      endDate: "Jun 2019",
      location: "Sydney, Australia",
      description: "Developed websites for small businesses and startups.",
    },
    {
      id: "exp-9",
      title: "Programming Tutor",
      company: "UNSW Sydney",
      employmentType: "Part-time",
      startDate: "Jul 2018",
      endDate: "Dec 2018",
      location: "Sydney, Australia",
      description:
        "Tutored undergraduate students in programming fundamentals.",
    },
    {
      id: "exp-10",
      title: "IT Support Intern",
      company: "Enterprise Solutions",
      employmentType: "Internship",
      startDate: "Jan 2018",
      endDate: "Jun 2018",
      location: "Sydney, Australia",
      description:
        "Provided technical support and maintained IT infrastructure.",
    },
  ],
  education: [
    {
      id: "edu-1",
      school: "University of New South Wales (UNSW)",
      schoolAbbreviation: "UNSW",
      degree: "Master of Information Technology",
      field: "Computer Science",
      startYear: "2020",
      endYear: "2022",
      logo: "https://media.licdn.com/dms/image/v2/C560BAQEbN-LbAZhZ-A/company-logo_100_100/company-logo_100_100/0/1630637066903?e=1762992000&v=beta&t=wP9JO0b1YJe0yRrZYPGP5oP1gZTuNq4dY0SQV4aXgKg",
    },
    {
      id: "edu-2",
      school: "University of New South Wales (UNSW)",
      schoolAbbreviation: "UNSW",
      degree: "Bachelor of Advanced Science (Hons)",
      field: "Computer Science",
      startYear: "2016",
      endYear: "2020",
      logo: "https://media.licdn.com/dms/image/v2/C560BAQEbN-LbAZhZ-A/company-logo_100_100/company-logo_100_100/0/1630637066903?e=1762992000&v=beta&t=wP9JO0b1YJe0yRrZYPGP5oP1gZTuNq4dY0SQV4aXgKg",
    },
    {
      id: "edu-3",
      school: "Stanford University",
      schoolAbbreviation: "Stanford",
      degree: "Machine Learning Specialization",
      field: "Artificial Intelligence",
      startYear: "2021",
      endYear: "2021",
    },
    {
      id: "edu-4",
      school: "MIT OpenCourseWare",
      schoolAbbreviation: "MIT",
      degree: "Introduction to Algorithms",
      field: "Computer Science",
      startYear: "2020",
      endYear: "2020",
    },
    {
      id: "edu-5",
      school: "Coursera",
      degree: "Full-Stack Web Development",
      field: "Web Development",
      startYear: "2019",
      endYear: "2019",
    },
    {
      id: "edu-6",
      school: "edX",
      degree: "Cloud Computing Fundamentals",
      field: "Cloud Computing",
      startYear: "2019",
      endYear: "2019",
    },
    {
      id: "edu-7",
      school: "Udacity",
      degree: "Data Structures and Algorithms Nanodegree",
      field: "Computer Science",
      startYear: "2018",
      endYear: "2018",
    },
    {
      id: "edu-8",
      school: "FreeCodeCamp",
      degree: "Responsive Web Design Certification",
      field: "Web Development",
      startYear: "2018",
      endYear: "2018",
    },
    {
      id: "edu-9",
      school: "Codecademy",
      degree: "Python Programming",
      field: "Programming",
      startYear: "2017",
      endYear: "2017",
    },
    {
      id: "edu-10",
      school: "Sydney High School",
      degree: "High School Diploma",
      field: "General Studies",
      startYear: "2012",
      endYear: "2016",
    },
  ],
  skills: [
    { id: "skill-1", name: "C++ (Programming Language)", endorsements: 15 },
    { id: "skill-2", name: "Go (Programming Language)", endorsements: 12 },
    { id: "skill-3", name: "Backend Programming", endorsements: 18 },
    { id: "skill-4", name: "Full-Stack Development", endorsements: 20 },
    { id: "skill-5", name: "Python (Programming Language)", endorsements: 25 },
    { id: "skill-6", name: "TypeScript", endorsements: 16 },
    { id: "skill-7", name: "React", endorsements: 22 },
    { id: "skill-8", name: "Node.js", endorsements: 19 },
    { id: "skill-9", name: "Docker", endorsements: 14 },
    { id: "skill-10", name: "Kubernetes", endorsements: 11 },
  ],
};

export const dimasPutra: User = {
  id: "dimas-putra",
  name: "Marcus Chen",
  title: "Forward Deployed Engineer @ Chakra",
  company: "Chakra",
  location: "Kingsford, New South Wales, Australia",
  avatar: "https://i.pravatar.cc/150?img=12",
  coverImage: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  isVerified: true,
  about:
    "Software Engineer and Master of Information Technology graduate at the University of New South Wales. I'm passionate about programming and exploring various technologies to create high-quality software solutions. My main interests are full-stack web development, backend programming, and data science.",
  connectionCount: 477,
  contactInfo: "dimas.putra@chakra.com",
  connectionDegree: "1st",
  currentCompany: "Chakra",
  regions: ["Asia Pacific"],
  experience: [
    {
      id: "exp-d1",
      title: "Forward Deployed Engineer",
      company: "Chakra",
      companyLogo: chakraCompanyLogo,
      employmentType: "Full-time",
      startDate: "May 2022",
      endDate: undefined,
      location: "Sydney, Australia",
      description:
        "Leading deployment initiatives and working closely with clients to deliver custom solutions.",
    },
    {
      id: "exp-d2",
      title: "Senior Software Engineer",
      company: "TechCorp Australia",
      employmentType: "Full-time",
      startDate: "Jan 2021",
      endDate: "Apr 2022",
      location: "Sydney, Australia",
      description:
        "Led a team of developers building enterprise applications using microservices architecture.",
    },
    {
      id: "exp-d3",
      title: "Software Engineer",
      company: "InnovateTech",
      employmentType: "Full-time",
      startDate: "Jun 2020",
      endDate: "Dec 2020",
      location: "Melbourne, Australia",
      description:
        "Developed cloud-native applications and implemented CI/CD pipelines.",
    },
    {
      id: "exp-d4",
      title: "Full Stack Developer",
      company: "WebWorks Pty Ltd",
      employmentType: "Full-time",
      startDate: "Jan 2020",
      endDate: "May 2020",
      location: "Sydney, Australia",
      description:
        "Built responsive web applications using React and Express.js.",
    },
    {
      id: "exp-d5",
      title: "Backend Engineer",
      company: "DataFlow Systems",
      employmentType: "Contract",
      startDate: "Jul 2019",
      endDate: "Dec 2019",
      location: "Remote",
      description:
        "Designed and implemented scalable backend systems for data processing.",
    },
    {
      id: "exp-d6",
      title: "Junior Developer",
      company: "AppStudio",
      employmentType: "Full-time",
      startDate: "Jan 2019",
      endDate: "Jun 2019",
      location: "Sydney, Australia",
      description: "Developed mobile and web applications for various clients.",
    },
    {
      id: "exp-d7",
      title: "Software Development Intern",
      company: "Tech Innovators",
      employmentType: "Internship",
      startDate: "Jul 2018",
      endDate: "Dec 2018",
      location: "Sydney, Australia",
      description:
        "Assisted in developing internal tools and customer-facing applications.",
    },
    {
      id: "exp-d8",
      title: "Web Development Intern",
      company: "Digital Agency Co",
      employmentType: "Internship",
      startDate: "Jan 2018",
      endDate: "Jun 2018",
      location: "Sydney, Australia",
      description:
        "Created websites and web applications for clients in various industries.",
    },
    {
      id: "exp-d9",
      title: "Programming Tutor",
      company: "Code Academy Sydney",
      employmentType: "Part-time",
      startDate: "Jul 2017",
      endDate: "Dec 2017",
      location: "Sydney, Australia",
      description:
        "Taught programming basics to beginners and helped students with coding projects.",
    },
    {
      id: "exp-d10",
      title: "IT Support Assistant",
      company: "University IT Department",
      employmentType: "Part-time",
      startDate: "Jan 2017",
      endDate: "Jun 2017",
      location: "Sydney, Australia",
      description:
        "Provided technical support to students and staff, maintained computer labs.",
    },
  ],
  education: [
    {
      id: "edu-d1",
      school: "University of New South Wales (UNSW)",
      schoolAbbreviation: "UNSW",
      degree: "Master of Information Technology",
      field: "Software Engineering",
      startYear: "2020",
      endYear: "2022",
      logo: "https://media.licdn.com/dms/image/v2/C560BAQEbN-LbAZhZ-A/company-logo_100_100/company-logo_100_100/0/1630637066903?e=1762992000&v=beta&t=wP9JO0b1YJe0yRrZYPGP5oP1gZTuNq4dY0SQV4aXgKg",
    },
    {
      id: "edu-d2",
      school: "University of New South Wales (UNSW)",
      schoolAbbreviation: "UNSW",
      degree: "Bachelor of Computer Science",
      field: "Software Development",
      startYear: "2016",
      endYear: "2020",
      logo: "https://media.licdn.com/dms/image/v2/C560BAQEbN-LbAZhZ-A/company-logo_100_100/company-logo_100_100/0/1630637066903?e=1762992000&v=beta&t=wP9JO0b1YJe0yRrZYPGP5oP1gZTuNq4dY0SQV4aXgKg",
    },
    {
      id: "edu-d3",
      school: "AWS Training",
      degree: "AWS Certified Solutions Architect",
      field: "Cloud Computing",
      startYear: "2021",
      endYear: "2021",
    },
    {
      id: "edu-d4",
      school: "Google Cloud",
      degree: "Professional Cloud Developer",
      field: "Cloud Development",
      startYear: "2021",
      endYear: "2021",
    },
    {
      id: "edu-d5",
      school: "Udemy",
      degree: "Microservices Architecture",
      field: "Software Architecture",
      startYear: "2020",
      endYear: "2020",
    },
    {
      id: "edu-d6",
      school: "Pluralsight",
      degree: "Advanced React Patterns",
      field: "Frontend Development",
      startYear: "2019",
      endYear: "2019",
    },
    {
      id: "edu-d7",
      school: "LinkedIn Learning",
      degree: "DevOps Foundations",
      field: "DevOps",
      startYear: "2019",
      endYear: "2019",
    },
    {
      id: "edu-d8",
      school: "Coursera",
      degree: "Docker and Kubernetes",
      field: "Container Orchestration",
      startYear: "2018",
      endYear: "2018",
    },
    {
      id: "edu-d9",
      school: "edX",
      degree: "Database Design",
      field: "Data Management",
      startYear: "2018",
      endYear: "2018",
    },
    {
      id: "edu-d10",
      school: "Melbourne High School",
      degree: "High School Certificate",
      field: "General Studies",
      startYear: "2012",
      endYear: "2016",
    },
  ],
  skills: [
    { id: "skill-d1", name: "Python (Programming Language)", endorsements: 22 },
    { id: "skill-d2", name: "Go (Programming Language)", endorsements: 18 },
    { id: "skill-d3", name: "Backend Programming", endorsements: 20 },
    { id: "skill-d4", name: "Microservices Architecture", endorsements: 17 },
    { id: "skill-d5", name: "AWS", endorsements: 21 },
    { id: "skill-d6", name: "Docker", endorsements: 19 },
    { id: "skill-d7", name: "Kubernetes", endorsements: 16 },
    { id: "skill-d8", name: "React", endorsements: 15 },
    { id: "skill-d9", name: "PostgreSQL", endorsements: 14 },
    { id: "skill-d10", name: "GraphQL", endorsements: 13 },
  ],
  highlights: [
    {
      id: "h1",
      type: "company",
      title: "You both work at Chakra",
      description: "Marcus Chen started at Chakra 5 months before you did",
    },
  ],
};

export const sameenJubayed: User = {
  id: "sameen-jubayed",
  name: "Elena Rodriguez",
  title: "Software Engineer",
  company: "Tech Corp",
  location: "Sydney, Australia",
  avatar:
    "https://media.licdn.com/dms/image/v2/D5603AQGURUj-NIGkrA/profile-displayphoto-shrink_100_100/profile-displayphoto-shrink_100_100/0/1718276129779?e=1762992000&v=beta&t=B0Y5anC-aT-fNoqMSY2pvF_W7dyUIZZ8DNsGmZ7Q5lk",
  coverImage: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  isVerified: true,
  about:
    "Passionate software engineer with experience in full-stack development and a keen interest in building scalable applications.",
  connectionCount: 350,
  contactInfo: "sameen.jubayed@example.com",
  connectionDegree: "2nd",
  currentCompany: "Google",
  regions: ["Asia Pacific"],
  experience: [
    {
      id: "exp-s1",
      title: "Software Engineer",
      company: "Tech Corp",
      employmentType: "Full-time",
      startDate: "Jan 2023",
      endDate: undefined,
      location: "Sydney, Australia",
      description:
        "Building modern web applications and contributing to open source projects.",
    },
    {
      id: "exp-s2",
      title: "Frontend Developer",
      company: "Digital Solutions",
      employmentType: "Full-time",
      startDate: "Jun 2022",
      endDate: "Dec 2022",
      location: "Sydney, Australia",
      description:
        "Developed responsive user interfaces using React and TypeScript.",
    },
    {
      id: "exp-s3",
      title: "Web Developer",
      company: "Creative Agency",
      employmentType: "Full-time",
      startDate: "Jan 2022",
      endDate: "May 2022",
      location: "Sydney, Australia",
      description: "Created websites and web applications for various clients.",
    },
    {
      id: "exp-s4",
      title: "Junior Developer",
      company: "StartUp Hub",
      employmentType: "Full-time",
      startDate: "Jul 2021",
      endDate: "Dec 2021",
      location: "Sydney, Australia",
      description:
        "Worked on full-stack web development projects in an agile team.",
    },
    {
      id: "exp-s5",
      title: "Software Development Intern",
      company: "TechNova",
      employmentType: "Internship",
      startDate: "Jan 2021",
      endDate: "Jun 2021",
      location: "Sydney, Australia",
      description:
        "Developed features for internal tools and customer-facing applications.",
    },
    {
      id: "exp-s6",
      title: "Frontend Intern",
      company: "WebFlow Studios",
      employmentType: "Internship",
      startDate: "Jul 2020",
      endDate: "Dec 2020",
      location: "Sydney, Australia",
      description:
        "Built UI components and implemented designs using modern frontend technologies.",
    },
    {
      id: "exp-s7",
      title: "Web Development Trainee",
      company: "Code Academy",
      employmentType: "Internship",
      startDate: "Jan 2020",
      endDate: "Jun 2020",
      location: "Sydney, Australia",
      description:
        "Learned web development fundamentals and built practice projects.",
    },
    {
      id: "exp-s8",
      title: "Tech Support Specialist",
      company: "IT Solutions Co",
      employmentType: "Part-time",
      startDate: "Jul 2019",
      endDate: "Dec 2019",
      location: "Sydney, Australia",
      description:
        "Provided technical support and troubleshooting for software issues.",
    },
    {
      id: "exp-s9",
      title: "Computer Lab Assistant",
      company: "UNSW Sydney",
      employmentType: "Part-time",
      startDate: "Jan 2019",
      endDate: "Jun 2019",
      location: "Sydney, Australia",
      description:
        "Assisted students with computer and software issues in university labs.",
    },
    {
      id: "exp-s10",
      title: "Retail Associate",
      company: "Tech Store",
      employmentType: "Part-time",
      startDate: "Jul 2018",
      endDate: "Dec 2018",
      location: "Sydney, Australia",
      description:
        "Provided customer service and technical advice on technology products.",
    },
  ],
  education: [
    {
      id: "edu-s1",
      school: "University of New South Wales (UNSW)",
      schoolAbbreviation: "UNSW",
      degree: "Bachelor of Engineering (Computer Science)",
      field: "Computer Science",
      startYear: "2018",
      endYear: "2022",
      logo: "https://media.licdn.com/dms/image/v2/C560BAQEbN-LbAZhZ-A/company-logo_100_100/company-logo_100_100/0/1630637066903?e=1762992000&v=beta&t=wP9JO0b1YJe0yRrZYPGP5oP1gZTuNq4dY0SQV4aXgKg",
    },
    {
      id: "edu-s2",
      school: "Coursera",
      degree: "Full-Stack Web Development Specialization",
      field: "Web Development",
      startYear: "2022",
      endYear: "2022",
    },
    {
      id: "edu-s3",
      school: "Udemy",
      degree: "Advanced React and Redux",
      field: "Frontend Development",
      startYear: "2022",
      endYear: "2022",
    },
    {
      id: "edu-s4",
      school: "LinkedIn Learning",
      degree: "TypeScript Essential Training",
      field: "Programming",
      startYear: "2021",
      endYear: "2021",
    },
    {
      id: "edu-s5",
      school: "FreeCodeCamp",
      degree: "JavaScript Algorithms and Data Structures",
      field: "Programming",
      startYear: "2021",
      endYear: "2021",
    },
    {
      id: "edu-s6",
      school: "Pluralsight",
      degree: "Node.js Path",
      field: "Backend Development",
      startYear: "2020",
      endYear: "2020",
    },
    {
      id: "edu-s7",
      school: "Codecademy",
      degree: "Web Development Career Path",
      field: "Web Development",
      startYear: "2020",
      endYear: "2020",
    },
    {
      id: "edu-s8",
      school: "edX",
      degree: "Introduction to Computer Science",
      field: "Computer Science",
      startYear: "2019",
      endYear: "2019",
    },
    {
      id: "edu-s9",
      school: "Khan Academy",
      degree: "Computer Programming",
      field: "Programming",
      startYear: "2019",
      endYear: "2019",
    },
    {
      id: "edu-s10",
      school: "Sydney Grammar School",
      degree: "High School Diploma",
      field: "General Studies",
      startYear: "2012",
      endYear: "2018",
    },
  ],
  skills: [
    { id: "skill-s1", name: "React", endorsements: 25 },
    { id: "skill-s2", name: "TypeScript", endorsements: 22 },
    { id: "skill-s3", name: "Node.js", endorsements: 18 },
    { id: "skill-s4", name: "JavaScript", endorsements: 28 },
    { id: "skill-s5", name: "HTML/CSS", endorsements: 24 },
    { id: "skill-s6", name: "Redux", endorsements: 17 },
    { id: "skill-s7", name: "Git", endorsements: 20 },
    { id: "skill-s8", name: "REST APIs", endorsements: 16 },
    { id: "skill-s9", name: "MongoDB", endorsements: 15 },
    { id: "skill-s10", name: "Agile Methodologies", endorsements: 14 },
  ],
};

export const allUsers: User[] = [
  currentUser,
  dimasPutra,
  sameenJubayed,
  { ...dimasPutra, id: "dimas-putra-2", name: "Marcus Chen 2" },
  { ...sameenJubayed, id: "sameen-jubayed-2", name: "Elena Rodriguez 2" },
];
